services:
  database:
    image: postgres:latest
    container_name: postgres-container
    env_file:
      - postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresdocker/

volumes:
  postgres_data:
